#!/bin/bash

cd ~/workspace/CM14.1-Nightly
export USE_CCACHE=1
export CCACHE_DIR=~/workspace/CM14.1-Nightly/.ccache
## END EDIT ##

prebuilts/misc/linux-x86/ccache/ccache -M 15G
prebuilts/misc/linux-x86/ccache/ccache -s
